spring.application.name=SJMT
server.port=3000
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://72.62.75.169:5432/sjmt_db?timezone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=admin@4321
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata