package com.sjmt.SJMT.Service;


import com.sjmt.SJMT.Entity.UserEntity;
import com.sjmt.SJMT.Entity.UserRoleEnum;
import com.sjmt.SJMT.Entity.UserStatusEnum;
import com.sjmt.SJMT.Repository.UserRepository;
import com.sjmt.SJMT.DTO.RequestDTO.LoginRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Objects;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;


    public String addNewUser(LoginRequest loginRequest){
        List<UserEntity> users = userRepository.findAll();
        for(UserEntity user: users){
            if (Objects.equals(user.getUsername(), loginRequest.getUsernameEmail()) || Objects.equals(user.getEmail(), loginRequest.getUsernameEmail())){
                return "User already exists";
            }
        }
        UserEntity newUser = new UserEntity();
        newUser.setUsername("aadhi");
        newUser.setEmail("aadhi@example.com");
        newUser.setPassword("hashedPassword123");  // Should be hashed
        newUser.setRole(UserRoleEnum.STAFF);
        newUser.setStatus(UserStatusEnum.ACTIVE);
// createdAt is auto-generated by @CreationTimestamp
// lastLogin starts as null
        userRepository.save(newUser);
        return "user Saved successfully";
    }
}
